# Generated by Django 4.2.5 on 2023-11-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='link_wpp',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='link_wpp',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='link_wpp',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='link_wpp',
            field=models.CharField(default='', max_length=500),
        ),
    ]
