# Generated by Django 4.2.5 on 2023-11-17 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_propriedadeapartamento_link_wpp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriedadeapartamento',
            name='link_wpp',
        ),
        migrations.RemoveField(
            model_name='propriedadecasaquarto',
            name='link_wpp',
        ),
        migrations.RemoveField(
            model_name='propriedadecasatoda',
            name='link_wpp',
        ),
        migrations.RemoveField(
            model_name='propriedadehotel',
            name='link_wpp',
        ),
    ]
