# Generated by Django 4.2.5 on 2023-11-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_configquartohotel_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propriedadehotel',
            old_name='empresa_faz_gestao_de_propriedades_ou_faz_parte_de_um_grupo_rede',
            new_name='grupo_rede',
        ),
    ]
