# Generated by Django 4.2.5 on 2023-12-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_empresa_faz_gestao_de_propriedades_ou_faz_parte_de_um_grupo_rede_propriedadehotel_grupo_rede'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiros',
            name='categoria',
            field=models.CharField(choices=[('restaurante', 'Restaurante'), ('supermercados', 'Supermercados'), ('farmacias', 'Farmácias'), ('hospitais', 'Hospitais'), ('turismo', 'Turismo')], default='', max_length=150),
        ),
    ]
