# Generated by Django 4.2.5 on 2023-12-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_parceiros_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiros',
            name='categoria',
            field=models.CharField(choices=[('n/a', 'N/A'), ('restaurante', 'Restaurante'), ('supermercados', 'Supermercados'), ('farmacias', 'Farmácias'), ('hospitais', 'Hospitais'), ('turismo', 'Turismo')], default='', max_length=150),
        ),
    ]
