# Generated by Django 4.2.5 on 2024-01-02 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_parceiros_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropriedadePousada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_propriedade', models.CharField(max_length=255)),
                ('pais_regiao', models.CharField(max_length=255)),
                ('nome_da_rua', models.CharField(max_length=255)),
                ('numero_residencia', models.CharField(max_length=10)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('local_de_dormir', models.CharField(max_length=255)),
                ('qtd_hospedes', models.CharField(max_length=10)),
                ('qtd_banheiros', models.CharField(max_length=10)),
                ('crianca_permissao', models.CharField(max_length=255)),
                ('oferece_bercos', models.CharField(max_length=255)),
                ('tamanho_da_propriedade', models.CharField(max_length=10)),
                ('tamanho_unidade', models.CharField(max_length=10)),
                ('o_que_pode_usar_na_propriedade', models.CharField(max_length=255)),
                ('serve_cafe_da_manha', models.CharField(max_length=10)),
                ('tem_estacionamento', models.CharField(max_length=10)),
                ('idiomas', models.CharField(max_length=255)),
                ('permitido_fumar', models.CharField(max_length=10)),
                ('bebidas_alcoolicas', models.CharField(default='Sim', max_length=10)),
                ('aceita_pets', models.CharField(max_length=10)),
                ('festas_eventos_permitidos', models.CharField(max_length=10)),
                ('tipo_de_cobranca', models.CharField(max_length=255)),
                ('valor_da_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('tipo_propriedade', models.CharField(default='pousada', max_length=255)),
                ('anfitriao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fotos',
            name='propriedade_pousada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.propriedadepousada'),
        ),
    ]
