# Generated by Django 4.2.5 on 2024-01-02 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_propriedadepousada_fotos_propriedade_pousada'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='propriedade_pousada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.propriedadepousada'),
        ),
    ]
