# Generated by Django 4.2.5 on 2024-01-03 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_reservas_propriedade_pousada'),
    ]

    operations = [
        migrations.AddField(
            model_name='configquartohotel',
            name='propriedade_pousada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.propriedadepousada'),
        ),
        migrations.AlterField(
            model_name='configquartohotel',
            name='propriedade_hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.propriedadehotel'),
        ),
    ]
