# Generated by Django 4.2.5 on 2024-01-03 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_configquartohotel_propriedade_pousada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configquartohotel',
            name='propriedade_pousada',
        ),
        migrations.RemoveField(
            model_name='fotos',
            name='propriedade_pousada',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='propriedade_pousada',
        ),
        migrations.DeleteModel(
            name='PropriedadePousada',
        ),
    ]
