# Generated by Django 4.2.5 on 2024-01-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_configquartohotel_propriedade_pousada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configquartohotel',
            name='area_externa_e_vista',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='configquartohotel',
            name='banheiro_privativo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='configquartohotel',
            name='comidas_e_bebidas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='configquartohotel',
            name='comodidades_gerais',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='configquartohotel',
            name='nome_do_quarto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='configquartohotel',
            name='permitido_fumar',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='configquartohotel',
            name='quais_camas_estao_disponiveis_neste_quarto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='configquartohotel',
            name='quais_itens_do_banheiro_esta_disponivel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='configquartohotel',
            name='qual_a_quantidade_de_quartos_deste_tipo_que_você_tem',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='configquartohotel',
            name='quntos_hospedes_podem_ficar_neste_quarto',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='configquartohotel',
            name='tamanho_do_quarto',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='configquartohotel',
            name='tamanho_unidade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='configquartohotel',
            name='tipo_de_unidade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='configquartohotel',
            name='valor_da_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='aceita_pets',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='bebidas_alcoolicas',
            field=models.CharField(blank=True, default='Sim', max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='cidade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='crianca_permissao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='estado',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='festas_eventos_permitidos',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='idiomas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='local_de_dormir',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='nome_da_propriedade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='nome_da_rua',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='numero_residencia',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='o_que_pode_usar_na_propriedade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='oferece_bercos',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='pais_regiao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='permitido_fumar',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='qtd_banheiros',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='qtd_hospedes',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='serve_cafe_da_manha',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='tamanho_da_propriedade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='tamanho_unidade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='telefone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='tem_estacionamento',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='tipo_de_cobranca',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadeapartamento',
            name='valor_da_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='aceita_pets',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='bebidas_alcoolicas',
            field=models.CharField(blank=True, default='Sim', max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='cidade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='crianca_permissao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='estado',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='festas_eventos_permitidos',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='idiomas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='local_de_dormir',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='nome_da_propriedade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='nome_da_rua',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='numero_residencia',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='o_que_pode_usar_na_propriedade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='oferece_bercos',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='pais_regiao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='permitido_fumar',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='qtd_banheiros',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='qtd_hospedes',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='serve_cafe_da_manha',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='tamanho_da_propriedade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='tamanho_unidade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='telefone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='tem_estacionamento',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='tipo_de_cobranca',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasaquarto',
            name='valor_da_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='aceita_pets',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='bebidas_alcoolicas',
            field=models.CharField(blank=True, default='Sim', max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='cidade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='crianca_permissao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='estado',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='festas_eventos_permitidos',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='idiomas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='local_de_dormir',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='nome_da_propriedade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='nome_da_rua',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='numero_residencia',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='o_que_pode_usar_na_propriedade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='oferece_bercos',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='pais_regiao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='permitido_fumar',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='qtd_banheiros',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='qtd_hospedes',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='serve_cafe_da_manha',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='tamanho_da_propriedade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='tamanho_unidade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='telefone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='tem_estacionamento',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='tipo_de_cobranca',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadecasatoda',
            name='valor_da_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='aceita_pets',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='bebidas_alcoolicas',
            field=models.CharField(blank=True, default='Sim', max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='cidade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='crianca_permissao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='estado',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='festas_eventos_permitidos',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='idiomas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='local_de_dormir',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='nome_da_propriedade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='nome_da_rua',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='numero_residencia',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='o_que_pode_usar_na_propriedade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='oferece_bercos',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='pais_regiao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='permitido_fumar',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='qtd_banheiros',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='qtd_hospedes',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='serve_cafe_da_manha',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='tamanho_da_propriedade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='tamanho_unidade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='telefone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='tem_estacionamento',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='tipo_de_cobranca',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propriedadehotel',
            name='valor_da_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
