# Generated by Django 4.2.5 on 2024-01-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_configquartohotel_area_externa_e_vista_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('titulo', models.CharField(blank=True, max_length=128, null=True)),
                ('conteudo', models.TextField(max_length=1024)),
                ('data_publicacao', models.DateField(auto_now=True)),
            ],
        ),
    ]
